CREATE TABLE EMP01(
	SABUN NUMBER PRIMARY KEY,
	NAME VARCHAR(15),
	DDATE DATE,
	SAL NUMBER
);

CREATE SEQUENCE EMP01_SEQ;

--DUMY DATA
INSERT INTO EMP01 values(EMP01_SEQ.NEXTVAL,'USER01',SYSDATE,1000);
INSERT INTO EMP01 values(EMP01_SEQ.NEXTVAL,'USER02',SYSDATE,2000);
commit;

select * from emp01;

